import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guide: [
    {
      type: 'category',
      label: '安装',
      link: {
        type: 'doc',
        id: 'install/index',
      },
      items: ['install/llqqnt'],
    },
    {
      type: 'category',
      label: '接入',
      link: {
        type: 'doc',
        id: 'connect/index',
      },
      items: ['connect/koishi'],
    },
  ],
  develop: [{ type: 'autogenerated', dirName: 'develop' }],
}

export = sidebars
